driver:
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    buttonpad:
        x: toggleManualShoot
        y: unlockClimber
    axes:
        leftTrigger: brakeMode
        rightTrigger: slowMode
    buttons:
        leftBumper: toggleCollectorReverse
        rightBumper: toggleCollector
        start: zeroPose
operator:
    rumble: false
    joysticks:
        left:
            horizontal: manualTurretXVal
            vertical: manualTurretYVal
        right:
            vertical: manualClimberArm
    dpad:
        up: raiseBucket
        down: lowerBucket
        left: turretJogLeft
        right: turretJogRight
    buttonpad:
        x: toggleCamera
        y: autoClimb
        a: getFieldFollowing # dummy for example purposes
        b: getSuperstructure # dummy for example purposes
    axes:
        leftTrigger: yeetShot
        rightTrigger: shoot
    buttons:
        leftBumper: autoAim
        start: toggleTopClamp
        back: toggleBottomClamp
