subsystems:
    drivetrain:
        implemented: true
        falcons:
            leftMain: 17
            leftFollower: 1
            leftFollowerTwo: -1
            rightMain: 14
            rightFollower: 15
            rightFollowerTwo: -1
        invertMotor:
            - leftMain
        pidConfig:
            slot0:
                kP: 0.1 # 0.18
                kI: 0.0001 # 0.018
                kD: 4.0 # 3.6
                kF: 0.0475813
        constants:
            maxTicks: 12275.7 # ticks per 100ms TODO tune - value currently from swerve
            encPPR: 22220.8
            openLoopRampRate: 0.8
            isSwerve: 0
    ledmanager:
        implemented: true
        canifier: -1
        candle: -1
        constants:
            raveEnabled: 1
            raveSpeed: 0.05
            cameraLed: 1
            maxLevel: 255
    turret:
        implemented: true
        pidConfig:
            slot0:
                kP: 1.25
                kI: 0.0003
                kD: 40.5
                kF: 0 # Should be 0 for position control
                allowableError: 40
        talons:
            turret: 33
        constants:
            deltaXScalar: 150 #value worked best at 150 in sim
            revLimit: 8800 # adjusted for zero-offset
            fwdLimit: 41500 # adjusted for zero-offset
            absPosTicksSouth: 0 # absolute
            zeroOffset: 12639 # (turretPPR - non-adjusted fwdLimit - non-adjusted revlimit) / 2
            encPPR: 4096
            turretPPR: 53248 # 4096 * 13
    shooter:
        implemented: true
        falcons:
            shooterMain: 21
            shooterFollower: -1
        invertMotor:
            - shooterMain
        solenoids:
            hood: 0
        pidConfig:
            slot0:
                kP: 0.38 #.45
                kI: 0.0002
                kD: 13.5 # 11 - 4.5
                kF: 0.0487
                allowableError: 100
        constants:
            usingPoseForSpeed: 0
            maxTicks: 20700
            nearVel: 4500
            midVel: 8450
            tarmacTapeVel: 8125
            launchpadVel: 10150
            maxVel: 16500
            coast: 8000
    climber:
        implemented: true
        falcons:
            climber: 34 #20
            climberFollower: 35 #-1
        solenoids:
            topClamp: 7
            bottomClamp: 6
        pidConfig:
            slot0:
                kP: 0.050 #0.075 #tunned at 4000
                kI: 0.000
                kD: .6
                kF: 0.0
                allowableError: 5000
        constants:
            maxTicks: 1
            unlockPos: -14400
            startPos: 0
            returnPos: 0
            firstToSecondRungPos: 150000
            secondToLastRungPos: 342000
            lastPos: 370000
    elevator:
        implemented: true
        talons:
            elevator: 32
        pidConfig:
            slot0:
                kP: 0.060
                kI: 0
                kD: 2
                kF: 0.05
                allowableError: 3000
        invertMotor:
            - elevator
        constants:
            isVelocity: 1
            maxTicks: 20000
            ballSensor: 0
            firePow: 0.35
            flushPow: -0.3
            intakePow: 0.3
    spindexer:
        implemented: true
        talons:
            spindexer: 31
        solenoids:
            feederFlap: -1
        constants:
            collectPow: 0.5
            indexPow: -0.5
            flushPow: -1
            coastPow: 0.25
            firePow: 0.85
    collector:
        implemented: true
        sparkmaxes:
            intake: 23 # maxTicks 10617
        invertMotor:
            - intake
        solenoids:
            arm: 2
        pidConfig:
            slot0:
                kP: 0.0001 #tunned at 4000
                kI: 0.0
                kD: 0.006
                kF: 0.0001
                allowableError: 10
        constants:
            revving: 0 #.05
            collecting: -5000 #-3600
            flush: 5000 #.35
    camera:
        implemented: true
        constants:
            debug: 0
            maxDist: 400
            maxDeltaX: 1200
            allowableDistanceError: 50
infrastructure:
    canivoreBusName: rio
    # power distribution
    pdId: 0
    pdIsRev: false
    # pneumatics control
    compressorEnabled: true
    pcmIsRev: false
    pcmId: 2
    # pigeon
    pigeonId: 13
    isPigeon2: false
constants:
    # drivetrain dimensions and movement
    maxRotVel: 7.2
    trackWidth: 21 #inches
    wheelbaseLength: 21.5 #inches
    wheelDiameter: 4
    kTrackScrubFactor: 1.0
    maxVelOpenLoop: 3 # meters/s
    maxVelPathFollowing: 2.2 # meters/s
    maxAccel: 2.54 # meters/s^ 2
    maxAllowablePoseError: 0.1
    ## Logging ##
    logTeleOp: 1 # 0 or 1
    logAuto: 1 # 0 or 1
    badLogEnabled: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    verbose: 0 # 0 or 1
    ## General ##
    EnableBucketTuning: 1
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .035 # seconds
    resetFactoryDefaults: 0 # whether motors get reset to factory default - if motors reset, rebooting the robot mid-match would kill the turret
