subsystems:
    drivetrain:
        implemented: true
        falcons:
            FLDr: 7
            FRDr: 10 #1
            RLDr: 18 #13
            RRDr: 15
            FLAz: 8
            FRAz: 11
            RLAz: 19
            RRAz: 14
        canCoders:
            FLEnc: 9 #TODO check values
            FREnc: 12
            RLEnc: 17
            RREnc: 16
        invertMotor:
            - FRDr
            - RRDr
        invertCanCoder:
            - FREnc
            - BREnc
        swerveModules:
            modules:
                frontLeft:
                    drive: FLDr
                    azimuth: FLAz
                    canCoder: FLEnc
                    constants:
                        encoderOffset: 1591
                        invertSensorPhase: 1
                frontRight:
                    drive: FRDr
                    azimuth: FRAz
                    canCoder: FREnc
                    constants:
                        encoderOffset: 1626
                        invertSensorPhase: 1
                backLeft:
                    drive: RLDr
                    azimuth: RLAz
                    canCoder: RLEnc
                    constants:
                        encoderOffset: 3120 #1539
                        invertSensorPhase: 1
                backRight:
                    drive: RRDr
                    azimuth: RRAz
                    canCoder: RREnc
                    constants:
                        encoderOffset: 2843
                        invertSensorPhase: 1
            drivePID:
                slot0:
                    kP: .3
                    kI: 0.0001
                    kD: 4.0
                    kF: 0.0499
            azimuthPID:
                slot0:
                    kP: 3.8 # 6.0
                    kI: 0.00075
                    kD: 77
                    kF: 0
                    allowableError: 5
        constants:
            maxVelTicks100ms: 12275.7 # ticks per 100ms
            openLoopRampRate: 0.8
            isSwerve: 1
            encPPR: 14255
            azimuthEncPPR: 4096
            maxRotVel: 14
            trackWidth: 21 #inches
            wheelbaseLength: 21.5 #inches
            wheelDiameter: 4
            kTrackScrubFactor: 1.0
            maxVelOpenLoop: 3 # meters/s
            maxVelPathFollowing: 3 # meters/s (2.2)
            maxAccel: 2.54 # meters/s^ 2
            isDemoMode: 0
    ledmanager:
        implemented: true
        canifier: -1
        constants:
            raveEnabled: 0
            raveSpeed: 0.05
            cameraLed: 1
            maxLevel: 255
    turret:
        implemented: true
        pidConfig:
            slot0:
                kP: 2.0
                kI: 0.0003
                kD: 30.5
                kF: 0 # Should be 0 for position control
                allowableError: 40
        talons:
            turretMotor: 33
        constants:
            deltaXScalar: 150 #value worked best at 150 in sim
            revLimit: -5580 # adjusted for zero-offset
            fwdLimit: 29600 # adjusted for zero-offset
            absPosTicksSouth: 200 # absolute
            absPPR: 4096
            turretPPR: 53248 # 4096 * 13
    shooter:
        implemented: true
        falcons:
            shooterMain: 21
        invertMotor:
            - shooterMain
        pidConfig:
            slot0:
                kP: 0.38 #.45
                kI: 0.0002
                kD: 13.5 # 11 - 4.5
                kF: 0.0487
                allowableError: 100
        constants:
            useLinearPiecewise: 0
            useCubicSpline: 0
            ballEjectionDuration: 0.9
            usingPoseForSpeed: 0
            maxVelTicks100ms: 20700
            nearVel: 4500
            midVel: 8650
            tarmacTapeVel: 8425
            launchpadVel: 10100
            maxVel: 16500
            coast: 8000
    climber:
        implemented: true
        falcons:
            climberMain: 34 #20
            climberFollower: 35 #-1
        invertMotor:
            - climberMain
        solenoids:
            topClamp: 6
            bottomClamp: 7
        pidConfig:
            slot0:
                kP: 0.035 #0.075 #tunned at 4000
                kI: 0.000
                kD: .6
                kF: 0.0
                allowableError: 3000
        constants:
            maxVelTicks100ms: 1
            unlockPos: 14400
            startPos: 0
            returnPos: 0
            firstToSecondRungPos: -150000
            secondToLastRungPos: -342000
            lastPos: -370000
    elevator:
        implemented: true
        talons:
            elevator: 32
        pidConfig:
            slot0:
                kP: 0.060
                kI: 0
                kD: 2
                kF: 0.05
                allowableError: 3000
        invertMotor:
            - elevator
        constants:
            isVelocity: 1
            maxVelTicks100ms: 20000
            ballSensor: 0
            firePow: 0.7
            flushPow: -0.3
            intakePow: 0.3
    spindexer:
        implemented: true
        talons:
            spindexer: 31
        constants:
            maxVelTicks100ms: 1
            collectPow: 0.5
            indexPow: -0.5
            flushPow: -1
            coastPow: 0.25
            firePow: 0.80
    collector:
        implemented: true
        talons:
            intake: 23 # maxVelTicks100ms 10617
        solenoids:
            arm: 2
        invertMotor:
            - intake
        pidConfig:
            slot0:
                kP: 0.1
                kI: 0.0
                kD: 0.1
                kF: 0.0001
                allowableError: 10
        constants:
            maxVelTicks100ms: 10000
            isVelocity: 0
            revving: 0 #.05
            collecting: -.5 #-3600
            flush: 0.5 #.35
    camera:
        implemented: true
        constants:
            debug: 0
            maxDist: 400
            maxDeltaX: 1200
            maxLoopCount: 3
            allowableDistanceError: 50
    cooler:
        implemented: true
        solenoids:
            lock: 1
            dump: 3
        constants:
            heatThreshold: 65 # degrees Celsius
infrastructure:
    canivoreBusName: highSpeed
    # power distribution
    pdId: 1
    pdIsRev: true
    # pneumatics control
    compressorEnabled: true
    pcmIsRev: false
    pcmId: 2
    # pigeon
    pigeonId: 13
    isPigeon2: true
controlboard: example
constants:
    # drivetrain dimensions and movement
    maxRotVel: 14
    trackWidth: 21 #inches
    wheelbaseLength: 21.5 #inches
    wheelDiameter: 4
    kTrackScrubFactor: 1.0
    maxVelOpenLoop: 3.2 # meters/s
    maxVelPathFollowing: 3.2 # meters/s (2.2)
    maxAccel: 2.54 # meters/s^ 2
    maxAllowablePoseError: 2
    ## Logging ##
    logTeleOp: 1 # 0 or 1
    logAuto: 1 # 0 or 1
    badLogEnabled: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    EnableBucketTuning: 1
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .035 # seconds
    resetFactoryDefaults: 0 # whether motors get reset to factory default - if motors reset, rebooting the robot mid-match would kill the turret

